/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define RCC_BASE     (0x40021000UL)
#define RCC_AHB2ENR  (*(volatile uint32_t *)(RCC_BASE + 0x4C))

#define GPIOB_BASE   (0x48000400UL)
#define GPIOB_MODER  (*(volatile uint32_t *)(GPIOB_BASE + 0x00))
#define GPIOB_AFRL   (*(volatile uint32_t *)(GPIOB_BASE + 0x20))

#define ITM_LAR      (*(volatile uint32_t *)(0xE0000FB0))

int main(void) {
	/*
	 * IMPORTANT NOTE!!!
	 * To make the ITM work enable SWD in debugger and set the Core Clock to 4MHz
	 * SWO baud rate = Core Clock / (TPIU prescaler + 1)
     * In the debugger settings:
     * Core Clock = 4,000,000 Hz
     * Prescaler = 1 (default)
     * SWO Baud Rate = 4,000,000 / 2 = 2,000,000 baud (2Mbps)
	 */
	// 1. Enable GPIOB port clock
	RCC_AHB2ENR |= (1 << 1);

	// 2. Configure PB3 as Alternate Function 0 (SYS_JTDO-SWO)
	GPIOB_MODER &= ~(3 << 6);   // Clear bits 6-7
	GPIOB_MODER |= (2 << 6);    // Set AF mode (10)
	GPIOB_AFRL &= ~(0xF << 12); // AF0 for pin 3 (bits 12-15)

	// 3. Special key to unlock ITM
	ITM_LAR = 0xC5ACCE55;       // Mandatory for L4 series

	printf("Message sent by ITM\n");

	/* Loop forever */
	for (;;);
}
